### ISSUE TITLE
Waterfall issues 

### ISSUE THREAD

**Issue by GrImIz1** [kirides/GD3D11#100]
CAN YOU FIX THIS AT THE WATERFALL

https://steamcommunity.com/sharedfiles/filedetails/?id=2812279717

MOD IS CALLED GOTHIC 1 DICCURIC

**Comment by GrImIz1** [comment]
let me know if you solve this bug

**Comment by GrImIz1** [comment]
are you fixing this

**Comment by Korikan** [comment]
Greetings, the devolopers of the mod need to assign the correct Material properties with the mapping function inside the spacer. The 'splash' faces for example arent supposed to be assigned as Water and so on, otherwise the renderer is going to apply the reflection effect on those faces.

**Comment by ThielHater** [comment]
@Korikan: What are the right material properties in your opinion? This is one of the oldest G1 mods, I doubt that there are any developers. The renderer has to handle this properly.

**Comment by SaulMyers** [comment]
I think this will be fixed if / when the change associated with this enhancement is implemented: https://github.com/kirides/GD3D11/issues/105

As mentioned above the waterfall splash shouldn't be rendered as water.

**Comment by SaulMyers** [comment]
Try again now, this should be fixed

**Comment by ThielHater** [comment]
This issue can be closed, thanks for your efforts. :)

**Comment by kirides** [comment]
@GrImIz1 please try out the latest build and see if your issue is now fixed
https://github.com/kirides/GD3D11/suites/8615539262/artifacts/386576033

feel free to re-open this issue if it still persists.
