### ISSUE TITLE
SOLVED [Linux] GothicStarter not working with ddraw on Native

### ISSUE THREAD

**Issue by cgloeckner** [kirides/GD3D11#103]
Hey guys,

I've been running Gothic 1 on Linux via Lutris for quite a while now and decided to try the Renderer.

In order to enable the renderer, I added `d3dcompiler_47.dll` and `ddraw.dll` as Native libraries in winecfg. Since then, the GothicStarter isn't launching Gothic anymore. As soon as I go back to the builtin `ddraw.dll`, Gothic 1 starts (but of course without the renderer)

A few more information:
- Gothic 1 is on `v1.08k_mod(SP 1.7)`
- Renderer `v17.8.0` from World of Gothic
- Wine Version is `lutris-6.0-x86_64` with DXVK `v1.7.3L-03f11ba`, VKD3D `v2.6`.
- GPU is NVIDIA GeForce GTX 1050 with NVIDIA's linux driver `470.141.03`
- Running on my Ubuntu machine with a `5.4.0` kernel

Running Lutris in debug mode yields no additional output when starting Gothic 1.
What's a good spot to look at for more information?

Greetings

**Comment by stefson** [comment]
I never tried Gothic1, but for Gothic2 you need to install dxvk libs (which you did), download the renderer and unpack it to the proper dir, and most important: overwrite `ddraw.dll` with `Native, Builtin` and ignore the warning. 

I'm using this version: https://github.com/kirides/GD3D11/releases/tag/v17.8-dev4-ci

Your dxvk libs are rather old by the way, it may not hurt to update them.

**Comment by cgloeckner** [comment]
Thanks, that's working!

**Comment by stefson** [comment]
Glad its now working for you, I believe its a bug in wine that only `Native, Builtin` makes the renderer work - `Native` alone should be fine as well, but thats not the case.
