### ISSUE TITLE
Sun jumps around in the sky

### ISSUE THREAD

**Issue by SaulMyers** [kirides/GD3D11#119]
The sun jumps around in the sky at certain times of the day. When the time changes from 11:59AM to 12PM for example, the sun will skip from one position to another, which is not cool. 

Does anyone know why this crazy maths was implemented to calculate the angle of the sun?

![image](https://user-images.githubusercontent.com/97944650/199828075-920cf8ac-f24a-4066-bbfb-c1606049e671.png)

If this much simpler calculation is uncommented then it all seems to work great - the sun is directly over header at 12PM and moves smoothly across the sky during the day.

![image](https://user-images.githubusercontent.com/97944650/199829196-df72cc1f-cd10-4587-8b76-fdd0701c5e4d.png)

This commented out code was introduced in these commits, but there is no information provided as to why it was added and why it wasn't actually implemented, so I'm assuming there's some issue I'm not aware of.

![image](https://user-images.githubusercontent.com/97944650/199828884-923e6d0c-de49-47d4-b25c-a4ec1c2ddaa1.png)

I'd really like the problem fixed though because I find it very jarring when the sun jumps around.

**Comment by lucifer602288** [comment]
I think Degenerated or Kirides should know it why it was this way implemented but from the past in the forum posts I remember that this implementation was dueto the time was this way in the code implemented and otherwise it would not be known which time of date it is. If you did test it several game days including the night and day changes, saving and loading of a savegame then just post the change. Could you provide an AVX2 dll of either Gothic 1 or 2 to test it?

**Comment by SaulMyers** [comment]
I don't have a range of saves to test it with but I've been playing G2 for a few days with the following code and it's working great:

`XMFLOAT3 GetSunWorldPosition( float timeScale = 1.0f ) {
        float angle = GetMasterTime() * XM_2PI; // Get mastertime into rad, 0 and 12 are now at the horizon, 18 is in the sky
        angle += XM_PIDIV2; // 12 is now in the sky, 18 horizon
        
        if ( timeScale <= -1 ) {
            angle = 4.71375f;
        } else {
            angle = angle * timeScale;
        }

        constexpr XMVECTORF32 sunPos = { -60, 0, 100, 0 };
        XMFLOAT3 rotAxis = XMFLOAT3( 1, 0, 0 );

        XMFLOAT3 pos;
        //XMVector3NormalizeEst leads to jumping shadows dueto reduced accuracy in combination with XMStoreFloat3( &LightDir, XMVector3NormalizeEst( XMLoadFloat3( &LightDir ) ) ); but setting this mentioned code line in this comment to non Est does not influence if this active code line before the comment is Est or not
        XMStoreFloat3( &pos, XMVector3TransformNormal( XMVector3Normalize( sunPos ), XMMatrixTranspose( XMLoadFloat4x4( &(HookedFunctions::OriginalFunctions.original_Alg_Rotation3DNRad( rotAxis, -angle )) ) ) ) );

        return pos;
    }`

AVX DLL attached as requested: 

[ddraw.zip](https://github.com/kirides/GD3D11/files/9970132/ddraw.zip)

**Comment by lucifer602288** [comment]
It seems to work under G2. Did you check it under G1?

**Comment by kirides** [comment]
@SaulMyers  please try the following build https://github.com/kirides/GD3D11/actions/runs/3436122125
it contains the mentioned changes

**Comment by SaulMyers** [comment]
Yes this looks good, thankyou for your efforts everyone. 

The sun still 'goes out' abruptly when it disappears completely over the horizon - 7PM based on the build above. It would be good if the sunlight strength gradually decreased before that time, in the same way as the sunlight strength is reduced when it's raining I guess.

I'll have a look at that one day when I have time.
