### ISSUE TITLE
Enhancements from another forks of GD3D11

### ISSUE THREAD

**Issue by pm4rcin** [Kirides/GD3D11#12]
Hi, there are some forks of the GD3D11 and I checked if any of them was enhanced. There's a list.

1. https://github.com/Katharsas/GD3D11/commit/01acfc447b02f7bccf5f19f6c8f15a7cfcd07e58
2. https://github.com/skydivin4ng3l/GD3D11/commit/058293bcc9fe4af4b23de46b657d5f19b553e4b5
3. https://github.com/MaxYari/GD3D11/commit/c6773f5e0f788b74a035dafa16313b13ea37ce57
4. https://github.com/MaxYari/GD3D11/commit/cc7df4cb61835c39600bedaa21c562b2ccd36716
5. https://github.com/biosmanager/GD3D11/commit/3a86e1a9f27dab3803435ed0d3cfa1504a07d00d

Also there's one repo with 18 new commits so I'll just provide a link for that.
https://github.com/ThielHater/GD3D11/commits/master

PS. You're doing great work. Can't wait to see new stable version. :)

**Comment by Kirides** [comment]
This renderer already includes the changes from Katharsas, many of the changes from skydivin4ng3l and the PolyStrips from MaxYari, aswell as a bunch of the changes from ThielHater.

:)
