### ISSUE TITLE
Game automatically stretches to fill the monitor in windowed mode

### ISSUE THREAD

**Issue by ezamelczyk** [kirides/GD3D11#123]
**Describe the bug**
When in Windowed or Fullscreen Borderless mode the game fills the full monitor no matter what resolution is set.

**To Reproduce**
1. Launch the Game
2. Set game to fullscreen borderless or windowed and change resolution to lower than native
3. Game fills the whole screen anyway

**Expected behavior**
The game should not resize itself. If I want to see the game in 10x10 resolution it should use only 100 pixels of my screen.

**Screenshots**

**Please complete the following information):**
 - Graphics card: GTX 1050 ti
 - Gothic version: G1, G2 Gold

**Additional context**
Every other game allows me to display the game in 1920x1080 on my ultrawide monitor with black bars but here I can only do this in fullscreen exclusive mode which does not work for me cause I also use the available space to display other things like twitch activity and chat.

**Comment by kirides** [comment]
See `Gothic\System\GD3D11\UserSettings.ini`

Modify the setting
```ini
[Display]
StretchWindow=1
```
and set it to `0` - the window should not be stretched anymore
