### ISSUE TITLE
Support for GOG version of Gothic2

### ISSUE THREAD

**Issue by stefson** [kirides/GD3D11#128]
hey there, 

today I decided to install the gog version of Gothic2, and after unpacking the renderer into ../system and installing the dxvk libs, it does give an error at starting Gothic2.exe which states: Gothic2 executeable not supported. 

I somehow remember this vaguely as a bit of a problem in the past, is this maybe fixed as of now in master branch?

**Comment by lucifer602288** [comment]
The GD3D11 is not with Gothic 2 Classic compatible, see this german forum post, it is compatible with Gothic 2 Night of the Raven (Gothic 2 with Addon):
https://forum.worldofplayers.de/forum/threads/1546222-Yet-Another-D3D11-Renderer/page58?p=27100757&viewfull=1#post27100757

**Comment by stefson** [comment]
The version sold on gog.com is the Gold Edition, which includes the Night of the Raven Addon. Its Version 2.7

https://www.gog.com/de/game/gothic_2_gold_edition

**Comment by stefson** [comment]
I'm happy to provide the checksum, if thats helpfull?

**Comment by lucifer602288** [comment]
Do you can still play Gothic 2 NotR?

**Comment by stefson** [comment]
I can play it sure, just not with the renderer.

**Comment by stefson** [comment]
I just reinstalled from Gold Edition DVD (Softwarepyramide), everything worked without a problem.
