### ISSUE TITLE
Skybox too small? Pink horizon!

### ISSUE THREAD

**Issue by im-charming** [Kirides/GD3D11#13]
Hello!

I have modded Gothic 1 slightly to run at full resolution with DirectX 11 using this [guide](https://steamcommunity.com/sharedfiles/filedetails/?id=484664831).

Everything works great so far (about 3-4 hours in), and I have disabled Atmospheric Scattering in order to get the original skybox back, in order to have the barrier work/appear.

However, the skybox doesn't seem to fit my resolution (1920x1080)? Images are [here](https://imgur.com/a/6D9fH8D):

My question is: is anyone familiar with this issue? Does anyone know a quick fix?

Options I've considered: do I need to make the skybox larger to fit, maybe by editing a file, or do I just make my view distance smaller so that I just can't see the band of just blank pink sky surrounding the lower horizon? I'm dubious about this second options, as I have attempted changing my view distance in the advanced DX11 options and the standard DX11 options, but that doesn't seem to work.

My standard DX11 options are [here ](https://imgur.com/a/b4vrVMy)

I haven't seen anyone with this same issue online.

EDIT: the white bar at the bottom of the screenshots is not the issue FYI - it is from me leaving space in paint when I pasted the screenshots ha!

I appreciate any help!

**Comment by pm4rcin** [comment]
I think it's how Piranhas made the game. I checked it without DX11 only with Union (System Pack) and it looks like the sky is on top, water on bottom and between them is that pink with atmospheric scattering. If you want to have a barrier you must edit the SystemPack.ini which is in Gothic/System folder and change the value AlwaysON=0 to AlwaysON=1. ;)
