### ISSUE TITLE
Is this safe?

### ISSUE THREAD

**Issue by LadySunx** [kirides/GD3D11#140]
I wanted to know if this was safe to use because virus total flagged two files as unsafe this is the link below.
Also sorry if there is a better way to dm about this i don't use github so im unfamiliar how to direct message or ask questions like this.
https://www.virustotal.com/gui/file/e60835c857927ac94269d4e7247517b20ffb0fb87ea2821eb8da532eca107cac/detection

**Comment by kirides** [comment]
Yes. This is safe.

You can assume if only a single vendor on virus total flags it, especially one as bad as Mc Afee.

i can only speak for builds in this Repository and only those which are under [Releases](https://github.com/kirides/GD3D11/releases).

**Comment by LadySunx** [comment]
Thank you! I just wanted to check and make sure also sorry if this was the wrong way to ask about this.
