### ISSUE TITLE
GD3D11 not working

### ISSUE THREAD

**Issue by ezamelczyk** [kirides/GD3D11#141]
I installed the game from steam, installed playerkit 1.8 playerkit 2.8 and systempack 1.8 then pasted the files from gd3d11 into the system folder. The game launches but without GD3D11. It just is not there and I've been trying many configurations with clean install without playerkit and systempack and with and just nothing works and I don't know what to do anymore.

**Comment by kirides** [comment]
I assume that you ...

1. went to `releases` (e.g. https://github.com/kirides/GD3D11/releases/tag/nightly) 
2. downloaded the current .ZIP (e.g. `GD3D11-git-01f98da79.zip`)
3. Have a base Gothic 2 installation with `Systempack 1.7+`/`Union 1.0h+`
4. Extracted the Zip (e.g. `GD3D11-git-01f98da79.zip`) into `...\Gothic 2\system\` such that the directory contains atleast ...  
   - `GD3D11` (Directory)
   - ...
   - `ddraw.dll`
   - ...
   - `Gothic2.exe`
   - ...

correct?

If you followed this, everything should work.

If you use Spine or any other Mod-Manager Tool, it would be better to ask in the Forum of that Tool.

**Comment by kirides** [comment]
I take your silence as an "everything works now", feel free to re-open the issue if it's still not working.
