### ISSUE TITLE
Name download assets generically

### ISSUE THREAD

**Issue by Reveares** [kirides/GD3D11#155]
If you name the download assests generically like `GD3D11.zip`, it will be possible to create a direct download link to the latest release like https://github.com/kirides/GD3D11/releases/latest/download/GD3D11.zip.
This can then be used on WoG and other platforms so that the common user is not overwhelmed by Github and the various files for assets. Also you don't have to constantly keep the link/description up to date.

**Comment by kirides** [comment]
Sure thing!

Will update the pipeline to include it.

**Comment by kirides** [comment]
should be implemented as of 534162b1d025f42c2e58f9b4ffc75118f758063f
