### ISSUE TITLE
[Gothic 1] [Nightly Build] Floating shadows on the ground in caves/mines and low quality player shadow in the same places (end of the video)

### ISSUE THREAD

**Issue by MarcinTomaszTomaszewski** [kirides/GD3D11#166]
**Describe the bug**
Just like in title, for better understanding please see the video.

**To Reproduce**
Go to old mine, the floating shadow bug will encounter in the entrance tunnel and then inside, in front of the first bridge.

**Expected behavior**
Floating shadows to be fixed. Also the pc-hero shadow to be the same quality as outdoors when selecting shadowmap of 16mb

**Screenshots**
Please see attached video: `https://www.youtube.com/watch?v=2ukTTfoE7Ys`

**Please complete the following information):**
 - Graphics card: RTX 4090
 - Gothic version: G1 vanilla with community patch 1.2 

**Additional context**
17.8 dev18 has the same issue, 17.8 dev12 has only slight overshoot in the entrance, but it was ok inside the mine. Player shadow quality however still was bugged.

**Comment by kirides** [comment]
i reverted the shader file that caused the issues for now.
the latest nightly will/should be ok again.

**Comment by MarcinTomaszTomaszewski** [comment]
Works nice! Thank you!
