### ISSUE TITLE
"Full-body" effects for NPCs

### ISSUE THREAD

**Issue by dosinabox** [kirides/GD3D11#169]
**Describe the bug**
"Full-body" effects are rendered in one point inside the NPC's model, instead of spreading equally. Examples:

```cpp
instance Dragon_Undead(Mst_Default_Dragon_Undead)
{
	...
	effect = "spellfx_undead_dragon";
	...
};

instance ITAR_FireArmor_Addon(C_Item)
{
	...
	effect = "SPELLFX_FIREARMOR";
	...
};
```

**To Reproduce**
```
insert Dragon_Undead
insert ITAR_FireArmor_Addon
```

**Expected behavior**
![362326288-6f6984dd-76c5-425e-a91e-b1384741009d](https://github.com/user-attachments/assets/9d86bc49-b8de-4836-9463-958dba3c90d4)

**Screenshots**
![362322125-bd656ca8-d650-45c7-a8f4-d9071e475ab6](https://github.com/user-attachments/assets/111e5154-f472-43bc-9c7f-3b2139f27298)

**Please complete the following information):**
 - Graphics card: `Nvidia GTX 1060`
 - Gothic version: G2 NotR 2.6 with Union 1.0m

**Comment by dosinabox** [comment]
Same for Fire Devils:
```cpp
instance Shadowbeast_Addon_Fire(Mst_Default_Shadowbeast_Addon_Fire)
{
	...
	effect = "SPELLFX_FIREARMOR";
};
```
![Screenshot_7](https://github.com/user-attachments/assets/12107a56-5149-49d6-bae8-5c1378adba89)

**Comment by dosinabox** [comment]
But for C_ITEM instances the effects are fine:

```cpp
instance ItRw_Addon_FireBow(C_Item)
{
	...
	effect = "SPELLFX_FIREBOW";
	visual = "ItRw_Bow_H_06.mms";
	...
};
```
![Screenshot_4](https://github.com/user-attachments/assets/7745eaa1-6268-4b3c-921d-c7e2cd1ee263)

**Comment by kirides** [comment]
At least the ones regarding the undead dragon (and possibly more) are fixed by @SaiyansKing

I'm currently in the process of merging a few sources back into this renderer.
Initially those changes will be incorporated. Afterwards further changes from @lucifer602288 and @Shoun2137 are likely.

Please try the following version first: https://github.com/SaiyansKing/GD3D11/releases/tag/v17.8-dev16

**Comment by dosinabox** [comment]
> Please try the following version first: https://github.com/SaiyansKing/GD3D11/releases/tag/v17.8-dev16

Works correctly!

![Screenshot_3](https://github.com/user-attachments/assets/5c722a19-64b4-49cf-9c7c-d127c3fc45b8)
![Screenshot_4](https://github.com/user-attachments/assets/35fcf343-afc6-41f5-88f9-0a8cce9ce4bd)
