### ISSUE TITLE
Allow persisting fog settings on a per world basis

### ISSUE THREAD

**Issue by dawidd4** [Kirides/GD3D11#17]
In Vanilla Gothic 1, the maximum View Range was 300%. But you still couldn't see Xardas tower, or the mountain fort from the cliff over the abandoned mine.
This DX 11 mod reveals too much, in my opinion.
My idea was to add fog in the distance. But every time I set the fog color and the range, after loading the game these settings keep resetting. Changes aren't persistent. Even in the `UserSettings.ini` file there are no entries for the fog parameters.

My wish would be that at least the view range was not that far, as default. Hidden by a fog wall. Like on the screen.
![image-150KB.jpg](https://user-images.githubusercontent.com/40753083/94619429-3105e600-02ad-11eb-9e02-a81805e8bc69.jpg)

**Comment by Kirides** [comment]
This is currently not supported due to Fog being non configurable.
To support this we would need to add a way to specify fog levels based on a "per world" basis like the renderer currently does hardcoded.

a way would be a `D3D11\\worlds\\WORLDNAME.ini` with the respective values.

**Comment by Kirides** [comment]
Implemented in current release

https://github.com/Kirides/GD3D11/releases/tag/v17.7-dev13
