### ISSUE TITLE
Cutscenes are not stretched after installing GD3D11

### ISSUE THREAD

**Issue by dawidd4** [Kirides/GD3D11#18]
I installed PlayerKit 1.08k, and SystemPack 1.8  for Gothic 1 (on 27th September 2020).
The cool thing was that with these Community Patches, the game looked good on any screen, be it on 4:3, 3:2, 16:9, etc.
Even the cutscenes were scaled to the screen size.

But after applying GD3D11, all cutscenes aren't full screen anymore. 1 pixel corresponds to 1 pixel again. Around the small video windows there is only black screen.

Is it possible to not overwrite the settings for cutscenes from SystemPack? I have no idea if it works that way.

**Comment by Kirides** [comment]
fixed with b2b496cc6
