### ISSUE TITLE
Random "Access Violation" errors.

### ISSUE THREAD

**Issue by Nuy** [Kirides/GD3D11#19]
I pretty often get Access Violation errors (every 20-30 minutes or so). It usually happens when I'm loading or saving the game but not only then. It only happens when I have DX11 installed and it happens to be with every version of it. My graphics card is Gigabyte GeForce GTX 1660 SUPER.

[Log.txt](https://github.com/Kirides/GD3D11/files/5476360/Log.txt)

**Comment by Kirides** [comment]
- Which version of the game?
- Are you playing with mods?
- Did you use the "4GB"-Hack / "LAA-Flag enabler" on the gothicmod.exe/gothic2.exe?

Can you please attach a DxDiag.txt


![5hhyjiA5t3_1](https://user-images.githubusercontent.com/13602143/97966208-d08e2b00-1dbb-11eb-9569-84af212d9c01.gif)

**Comment by Nuy** [comment]
Game version is 2.6 with installed fix, player kit and system pack. The only mod I have is L'Hiver. Do I need to have any normalmaps installed with this version of DX11?

[DxDiag.txt](https://github.com/Kirides/GD3D11/files/5481812/DxDiag.txt)

**Comment by Kirides** [comment]
normalmaps take away too much precious memory for Gothic, especially on mods like L'Hiver.

you should apply the "LAA-Hack" / 4GB Patch to your `gothic2.exe` and make sure you don't have "Dynamic shadows" all the way to the right.

**Comment by Nuy** [comment]
I have "LAA-Hack" applied and it's still the same. When it's not applied I get "Out of Memory" error and when it's applied it's "Access Violation" so it's some memory error I guess but it only happens when i have DX11 installed.

**Comment by Nuy** [comment]
![Gothic2_2Ab5AiuPww](https://user-images.githubusercontent.com/4800827/98061973-6aea7f00-1e4d-11eb-9fe8-898a84d097f6.png)

Same thing happens. :/

**Comment by Kirides** [comment]
The error message looks more like the mod has an issue, or a Patch/Plugin.

**Comment by Nuy** [comment]
It only happens when DX11 is installed tho.

**Comment by Kirides** [comment]
closed due to inactivity.
