### ISSUE TITLE
Add github actions workflow

### ISSUE THREAD

**Issue by G00fY2** [Kirides/GD3D11#22]
Since BonneCW appveyor workflow is private. We should consider adding a github actions workflow, maybe with PR checks and linter.

Maybe I find time to setup the workflow.

**Comment by BonneCW** [comment]
Oh, didn't know it's private. Can have a look on it later to make it public

**Comment by G00fY2** [comment]
@BonneCW that would be great. But even then the workflow would not work for this fork e.g. The advantage of using github actions that I see is, that everyone can run and may customize the workflow, even after forking. :)

**Comment by G00fY2** [comment]
@BonneCW any news about this?

But I would still love to see automatic builds using GitHub Actions and deployments to GitHub Releases. Unfortunately I am not familiar with setting this up for C++ projects.
