### ISSUE TITLE
After v17.7-dev13 build rain particles aren't rendered in G2NR.

### ISSUE THREAD

**Issue by pm4rcin** [Kirides/GD3D11#23]
As in title now there's no rain particles. Steps to reproduce:
1. Load game without DX11 (Union only), open console and type zstartrain. The particles are rendered normally.
2. Load game with DX11 and Union, open console and type zstartrain. There are no particles.

**Comment by Kirides** [comment]
Yep i made a mistake, it fixed with 415b812c61b8a4a12 and is available with release dev-14
