### ISSUE TITLE
Incorrect shadow map size on load

### ISSUE THREAD

**Issue by plrusek** [Kirides/GD3D11#24]
If I set shadow map size to something bigger than default (seems to be 2048?), in my case 16384, it works just fine. However, saving it and then opening the game up again - it still says I'm on 16384 shadow map size but very clearly it's not 16384 but more like back to 2048. So - the setting for 16384 becomes 2048 and it goes down proportionally from there. So - what used to be 256 would now be as low as 32 or something if I set that after loading up the game with an .ini.

Similarly, if I set shadow map to 256 and then restart the game and use the slider to increase, 16384 actually becomes like 128k, very crisp shadows.

I have only tested Gothic 1 so far with Systempack 1.8 (with required playerkits and patches 1.08k)

**Comment by donmarczello** [comment]
I have the same.
I confirm.


Temporary solution:
At the end of the game, set the slider to the lowest value.
When you restart the game, you move the slider to your own value.

**Comment by Kirides** [comment]
I confirm this issue.

The "WorldShadowRangeScale" is not properly set on save/load and changing the shadow values.

A dev15-fix2 version will be available shortly after testing.

**Comment by Kirides** [comment]
fixed with [v17.7-dev15-fix2](https://github.com/Kirides/GD3D11/releases/tag/v17.7-dev15-fix2)
