### ISSUE TITLE
G3D11 renderer is shipped with funny/broken d3dcompiler_47.dll since 17.7-dev12

### ISSUE THREAD

**Issue by stefson** [Kirides/GD3D11#25]
As I was really struggeling with an answer to the problem of d3dcompiler_47.dll, and why wine rejected to load it, I tried to poke it with something like `ldd` to find out more about its dependencies. Since I'm still on the linux machine, it seemed reasonable to poke it with i686-w64-mingw32-objdump -p just to learn more about it. Turned out i686-w64-mingw32-objdump flakes when trying to process the non loading d3dcompiler_47.dll

now, that's a point at least. Maybe it's wrong file format? 

here is my evidence for dev12 and follow ups: 
```
file *.dll
AntTweakBar.dll:            PE32 executable (DLL) (console) Intel 80386, for MS Windows
GFSDK_SSAO_D3D11.win32.dll: PE32 executable (DLL) (GUI) Intel 80386, for MS Windows
assimp-vc142-mt.dll:        PE32 executable (DLL) (console) Intel 80386, for MS Windows
d3dcompiler_47.dll:         PE32+ executable (DLL) (console) x86-64, for MS Windows
ddraw.dll:                  PE32 executable (DLL) (GUI) Intel 80386, for MS Windows
```

for not broken dev11-fix-2: 

```
file *dll
AntTweakBar.dll:            PE32 executable (DLL) (GUI) Intel 80386, for MS Windows
GFSDK_SSAO_D3D11.win32.dll: PE32 executable (DLL) (GUI) Intel 80386, for MS Windows
assimp-vc142-mt.dll:        PE32 executable (DLL) (console) Intel 80386, for MS Windows
d3dcompiler_47.dll:         PE32 executable (DLL) (console) Intel 80386, for MS Windows
ddraw.dll:                  PE32 executable (DLL) (GUI) Intel 80386, for MS Windows
```

so, yes, this is x86_64 dll, shipped since 17.7-dev12

there is a tool for windows that is ldd like, called dependency walker: http://dependencywalker.com/ after installing it on my old win7 and opening the d3dcompiler_47.dll, I'm not even sure what to say about this frankenstein dll. 

can you please ship the correct x86 dll instead with the next release? and maybe drop it here, if you need actuall runtime testing from users? that would be fantastic

**Comment by Kirides** [comment]
oh, you are totally right!
I will publish a fixed version ASAP.

**Comment by Kirides** [comment]
Fixed with [v17.7-dev15-fix1](https://github.com/Kirides/GD3D11/releases/tag/v17.7-dev15-fix1)

**Comment by stefson** [comment]
Do you think you're able to share more information about this d3dcompiler_47.dll file? I thought all those dll files are the result of you compiling the source code, but that doesn't seem to be the case here, right? 

cause what the Gothic2.exe propably is doing here is to load the dll files from the folder first, before checking out other lib path.

**Comment by Kirides** [comment]
the d3dcompiler_47.dll is used to compile the used shaders at runtime.

i deploy the latest available version of it with the renderer. Because some systems do not come shipped with it.

**Comment by stefson** [comment]
so, from my understanding how this works: 

Gothic2.exe needs d3dcompiler_47.dll at runtime and starts looking at the same file directory it is placed in, which is C:\Program Files\Jowood\Gothic II Gold\System\ , and gets all cranky about wrong x86_64 dll. 
If Gothic2.exe can't find d3dcompiler_47.dll in the same dir, it will have a look in the dir Windows stores it's dll files, that should be C:\Windows\system32\ 
If Gothic2.exe can find a suitable d3dcompiler_47.dll in it's own directory, it will happily use that and ignore C:\Windows\system32\ 
Also it is not very picky, and happily makes use of a win10 d3dcompiler_47.dll even if wine is running on Win7

**Comment by Kirides** [comment]
Yes. This is basic windows dll loading in a nutshell.
It is not specific to the Game, or any other application.
