### ISSUE TITLE
G1 dx11 bug-error in animations

### ISSUE THREAD

**Issue by donmarczello** [kirides/GD3D11#27]
I am reporting a bug.
Looks like this in the attached photos.
When I talk to the NPC, he interrupts the activity, e.g. cooking, and when he cooks again, errors occur.

![1_Cooking](https://user-images.githubusercontent.com/40342060/101377256-e195f480-38b1-11eb-9472-c29b49d942c3.png)
![2_Pick](https://user-images.githubusercontent.com/40342060/101377275-e78bd580-38b1-11eb-81b0-9d9eaeffee8a.png)
![3_Saw](https://user-images.githubusercontent.com/40342060/101377289-ed81b680-38b1-11eb-8401-b3697711e39c.png)
![4_](https://user-images.githubusercontent.com/40342060/101377323-f4102e00-38b1-11eb-8087-bdc176ba731b.png)

**Comment by donmarczello** [comment]
Can you fix it Kirides?
It would be great.

**Comment by kirides** [comment]
Should be fixed as of v17.8-dev1
