### ISSUE TITLE
error in GD3D11\D3D11Engine\D3D11ShaderManager.cpp(545) with Gothic2 and GD3D11-17.7-dev15-fix2

### ISSUE THREAD

**Issue by stefson** [Kirides/GD3D11#30]
I just noticed this when reading through the logs: 

```
Info: Compilling hull shader: system\GD3D11\shaders\DefaultTess.hlsl
Info: Shader compilation failed!
Info: Compilling hull shader: system\GD3D11\shaders\DefaultTess.hlsl
Info: Shader compilation failed!
Error: [E:\Dev\GD3D11\D3D11Engine\D3D11ShaderManager.cpp(545), enum XRESULT __thiscall D3D11ShaderManager::CompileShader(const struct ShaderInfo &)]: 1 failed with code: 1 (General fail)
Info: Compilling hull shader: system\GD3D11\shaders\OceanTess.hlsl
``` 

hope it is helpfull for you :-)  

the full log: [Log.txt.zip](https://github.com/Kirides/GD3D11/files/5661802/Log.txt.zip)  shows some more warnings, some of which sound rather severe (something started loading before the engine was ready, for instance)

**Comment by stefson** [comment]
this is the same log from Win7 via spine client, I'm not sure if they use your binaries. But it's the same error, same lines: 

```
Info: Compilling hull shader: system\GD3D11\shaders\DefaultTess.hlsl
Info: Shader compilation failed!
Info: Compilling hull shader: system\GD3D11\shaders\DefaultTess.hlsl
Info: Shader compilation failed!
Error: [E:\Projects\GD3D11\D3D11Engine\D3D11ShaderManager.cpp(545), enum XRESULT __thiscall D3D11ShaderManager::CompileShader(const struct ShaderInfo &)]: 1 failed with code: 1 (General fail)
Info: Compilling hull shader: system\GD3D11\shaders\OceanTess.hlsl
```

[Log.txt.zip](https://github.com/Kirides/GD3D11/files/5667377/Log.txt.zip)

**Comment by Kirides** [comment]
The error is nothing to worry about. This shader is not used anywhere.It was already removed from the code base but slipped back in in a rework.Am 09.12.2020 17:47 schrieb stefson <notifications@github.com>:
this is the same log from Win7 via spine client, I'm not sure if they use your binaries. But it's the same error, same lines:
Info: Compilling hull shader: system\GD3D11\shaders\DefaultTess.hlsl
Info: Shader compilation failed!
Info: Compilling hull shader: system\GD3D11\shaders\DefaultTess.hlsl
Info: Shader compilation failed!
Error: [E:\Projects\GD3D11\D3D11Engine\D3D11ShaderManager.cpp(545), enum XRESULT __thiscall D3D11ShaderManager::CompileShader(const struct ShaderInfo &)]: 1 failed with code: 1 (General fail)
Info: Compilling hull shader: system\GD3D11\shaders\OceanTess.hlsl

full log: Log.txt.zip

**Comment by Kirides** [comment]
This shader is now again commented out in the code.

**Comment by stefson** [comment]
thanks for the fix, do you think its possible to push out a new binary then? I'm not sure how your workflow usually is, are you facing some issues that made you skip 17.7-dev16?

**Comment by Kirides** [comment]
Dev16 is currently being actively tested.Am 20.12.2020 19:47 schrieb stefson <notifications@github.com>:
thanks for the fix, do you think its possible to push out a new binary then? I'm not sure how your workflow usually is, are you facing some issues that made you skip 17.7-dev16?
