### ISSUE TITLE
little 4K/DSR problems

### ISSUE THREAD

**Issue by plrusek** [Kirides/GD3D11#31]
Hello, first off - thanks for fixing issue #24 a while back. secondly - thanks for making this fork of GD3D11 being able to use 4K resolution on 1080p monitor - I'm using NVIDIA's DSR to enable this for better antialiasing than SMAA.

However there's three little problems with it still:
1. Similarly to the old issue with shadow maps, the resolution does not save properly. It's set to 3840x2160 in the config file but the game always stars in 1080p (native monitor res)
2. After setting the 4K res in config menu ingame, the GUI is cut off and only 1/4th of it is visible - the top left half. I imagine as a result from going from 1080p to 4K it messed it up somehow. Setting the UIScale value from 1 to 2 fixes it and it even looks like it did on 1080p scale wise, but I imagine this cut-off thing shouldn't happen and the UI should've just remained small.
![image](https://user-images.githubusercontent.com/18425248/102875221-d4e1d680-4443-11eb-94d9-815843c0aa43.png)
3. The advanced settings (present in the image above) are misaligned with my actual mouse position, making it hard to set anything. It feels like my mouse movement corresponds once again to the first 1/4th of the screen. Does not happen with the regular settings menu.

Thank you again for developing this renderer further.

**Comment by Kirides** [comment]
Known issue, after setting the resolution from ingame slider, press apply and restart the game
