### ISSUE TITLE
WQHD - inventory visibility problems

### ISSUE THREAD

**Issue by axel-dd** [Kirides/GD3D11#36]
In WQHD - 2.560 x 1.440 there are inventory visibility problems. Both in G1 and G2. 
In Full HD everything works great.

![inventory-not-visible](https://user-images.githubusercontent.com/6698567/109860264-343b3e80-7c5e-11eb-9c6f-f2905a17255b.png)

![g2_inventory-bug](https://user-images.githubusercontent.com/6698567/109860259-31d8e480-7c5e-11eb-9b32-631b55d14270.png)

**Comment by Kirides** [comment]
What renderer are you using?It's not one of my latest versions.I play in 2560x1440 and all is good.I need to know the exact renderer version as well as Systempack, union, used mods, texture patches, etc.

**Comment by axel-dd** [comment]
### Gothic 2

![image](https://user-images.githubusercontent.com/6698567/109870644-a6198500-7c6a-11eb-9f63-0855c3db9139.png)

Patch 2.6
Gothic 2 Playerkit 2.8
G2NoTR-SystemPack-1.8 + v1.9 pre2 DLL only release
G3D11 Renderer v17.7-dev16
Ninja-2.4.09
ninja-quickloot v1.8.11
[MiniMod Balance](https://www.worldofgothic.de/dl/download_208.htm)
[G2-High-Vegetation-Mod](https://forum.worldofplayers.de/forum/threads/1481107-RELEASE-G2-High-Vegetation-Mod) - GraphicPatch_Advanced.vdf + updated Normalmaps + Minimod Balance Update + Zusätzliche Normalmaps für Minimod Update

----------------------------

### Gothic 1

Patch 1.08k
Gothic 1 Playerkit 1.08k
G1Classic-SystemPack-1.8.exe
G3D11 Renderer v17.7-dev16
[Definitive_Edition v1.4.5](https://www.worldofgothic.de/dl/download_635.htm)

**Comment by axel-dd** [comment]
I also tested G1 and G2 in WQHD without mods.
G2 without mods - no visibility problems
G1 without mods - same problems as with the Definitive Edition

**Comment by Kirides** [comment]
@axel-dd some people messaged me about incompatibilites with `Animated_Inventory` of Systempack.

Could you try to set `Animated_Inventory=0` in `Systempack.ini` (G1)

**Comment by axel-dd** [comment]
It seems the Inventory problems disappear if your restart the game directly after resolution change. 
I deleted the UserSettings.ini and tried the following...
With the default settings and the resolution change to WQHD, the visibility problems of the inventory occur. But when I restart the game the problems are gone. So I think you can close this issue.

OK now to your request...
I have no problems with Animated_Inventory=0 or 1 in WQHD with my configuration above. Tested without mods and with Definitive Edition v1.4.5

**Comment by Kirides** [comment]
Oh, so it's just that you used the custom resolution feature without restarting, i see.

It causes a bunch of UI issues with Gothic and one should always restart the game after hitting apply.

I will add this to the known issues, but probably won't spend time on fixing it myself.
