### ISSUE TITLE
White Screen after startup

### ISSUE THREAD

**Issue by VirtualAI** [Kirides/GD3D11#38]
Hello,

issue happens both with G1 and G2. I did a clean install on Gothic1, 1,08k Patch, Player Kit, System Kit,  Direct X11 Mod.
When i start the game, i hear sound, i can access the render-settings, but every thing else is white. I'm using a notebook with iGPU and Nvidea Mobile GPU (Dell Inspirion). 
Thanks very much. Without DX11 renderer, everything is working.
Best regards.

**Comment by Kirides** [comment]
you have to run the game with your Nvidia GPU.

Whitescreen is caused by intel iGPU not supporting certain features.

**Comment by VirtualAI** [comment]
Thank you very much, it worked.
Are there any plans in the future to make it work on iGPu only devices?
