### ISSUE TITLE
draws & performance

### ISSUE THREAD

**Issue by lechu2375** [Kirides/GD3D11#42]
2D Draws causes fps drop, as example I can give Gothic Online and chat.

**Comment by Kirides** [comment]
In the `UserSettings.ini`, try out 
```ini
# ...
[FontRendering]
Enable=1
# ...
```

**Comment by lechu2375** [comment]
I don't see anything major, only changed font for text when Im typing new message before sending it.
You have done this for GMP or Gothic Online? Maybe they have diffrent methods to draw chat messages.

**Comment by lechu2375** [comment]
What I should point that font was changed only for draws that I had from my Union plugin.

**Comment by Kirides** [comment]
`FontRendering` captures all calls that draw characters on the screen and reduces the amount of drawcalls immensly.

But it will also be incompatible with Plugins that override default font-draw calls (_not_ just drawing plugins, but ones that replace drawing behaviour), because they override the hook address.

**Comment by lechu2375** [comment]
It was only issue on Gothic Online. My union plugins just shows two draws.
![image](https://user-images.githubusercontent.com/26012904/114359542-5fc21a80-9b74-11eb-99da-52400aeb77cd.png)
Here, if you are curious about changed font. Chat has default font before enabling font rendering option.

**Comment by lechu2375** [comment]
Spring OFF comes from union plugin, the rest is Gothic Online.

**Comment by lechu2375** [comment]
Also Gothic_14.spritefont does not supports polish characters, but I think it is only about changing it in config.

**Comment by Kirides** [comment]
`Gothic_14.spritefont` does not exist anymore. The entry in the UserSettings.ini does nothing and can be deleted.

What renderer version do you use?
i only support the latest https://github.com/Kirides/GD3D11/releases/tag/v17.7-dev16

**Comment by lechu2375** [comment]
Gothic 2 ofc, I use latest release.
