### ISSUE TITLE
White little dots while playing problem

### ISSUE THREAD

**Issue by pm4rcin** [kirides/GD3D11#47]
The white dots are visible when playing. They flicker a bit and shouldn't be there.
![huj2](https://user-images.githubusercontent.com/37148802/116470545-173c7980-a863-11eb-8993-20241b3255cd.png)

**Comment by Feldknoeterich** [comment]
I ran into the same graphical artifacts and turning off "Draw Fog" under the advanced options seems to fix it. Maybe this helps with identifying the issue.

**Comment by pm4rcin** [comment]
> I ran into the same graphical artifacts and turning off "Draw Fog" under the advanced options seems to fix it. Maybe this helps with identifying the issue.

A friend of mine can confirm.

**Comment by stefson** [comment]
I can recall to have seen them as well while playing, but found them to be just a very minor inconvenience.

**Comment by pm4rcin** [comment]
I've just checked today on the same spot and I can't see them anymore so it was probably fixed since then.
