### ISSUE TITLE
Gothic 1 on Linux - game crashes after I load my savegames

### ISSUE THREAD

**Issue by bodzioslav** [Kirides/GD3D11#51]
I have installed a fresh installation of Gothic with SystemPack 1.8 and PlayerKit (`gothic1_playerkit-1.08k.exe`) on Wine 32 bit prefix with the following version of GD3D11: `Gothic1-GD3D11-17.7-dev11-fix2.zip` and the newest dxvk release. 

Wine version: wine-6.8 (Staging)
OS: Linux Ubuntu 21.04
Kernel: 5.8.0-50-generic x86_64

CPU: AMD Ryzen 5 2600
GPU: AMD Radeon RX580
RAM: 16GB DDR4 

List of winetricks packages I'm using:
```
d3dcompiler_43
d3dx9
dxvk181
dmband
dmcompos
dmime
dmloader
dmscript
dmstyle
dmsynth
dmusic
dmusic32
dsound
dswave
directmusic
```
I configured library overrides in winecfg for `ddraw (native, bultin)`, `d3d_compiler47 (native, builtin)` and `dsound (builtin, native)`. I also tried 64bit prefix but no luck.

The game just throws the following error after I load any of my savegames: or after I try to start a new game:
```
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
warn:  D3D11Device::CreateShaderModule: Class linkage not supported
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  1920x1080
info:    Image count:  3
info:    Exclusive FS: 2
0024:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.
err:   D3D11RasterizerState: Antialiased lines not supported
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

abnormal program termination
0024:fixme:ntdll:EtwEventUnregister (deadbeef) stub.
0024:fixme:ntdll:EtwEventUnregister (0) stub.
```
I attach log files from my `System` directory:

[GothicMod_d3d11.log](https://github.com/Kirides/GD3D11/files/6526360/GothicMod_d3d11.log)
[GothicMod_dxgi.log](https://github.com/Kirides/GD3D11/files/6526361/GothicMod_dxgi.log)
[sp.log](https://github.com/Kirides/GD3D11/files/6526362/sp.log)
[GothicMod_d3d9.log](https://github.com/Kirides/GD3D11/files/6526363/GothicMod_d3d9.log)
[Log.txt](https://github.com/Kirides/GD3D11/files/6526364/Log.txt)

**Comment by Kirides** [comment]
`Failed to open custom Mesh: system\GD3D11\meshes\unitSphere.obj`

There seems to be an issue with your installation. I'd assume that could be due to gothic being installed in `C:\PROGRAM FILES\` but i don't know about that and linux.
