### ISSUE TITLE
Implement this Renderer-version in Spine-Mod-Manager

### ISSUE THREAD

**Issue by progward** [Kirides/GD3D11#53]
Many people who are playing Gothic only with Spine don't use your Renderer, because it isn't available in Spine. There you also have the very easy option to play with or without Renderer by one single mouseclick. I think you'd have to contact Bonne, he is the dev of Spine.

**Comment by Kirides** [comment]
That's none of my business.

Bonne merges versions that are considered "stable" to his GD3D11 version. Thus once enough people play and test a version, bonne will merge the changes and people get to play with a "newer" version
