### ISSUE TITLE
dark night

### ISSUE THREAD

**Issue by JDFiX** [Kirides/GD3D11#56]
If there is a way to make the night brighter?

**Comment by Kirides** [comment]
Night should be bright enough in latest releases. If that doesn't help:Reduce contrast, try out HDR, get your screen properly calibrated with a proper viewing angle, further increase the night brightness and suffer from shining dawn and noon.Am 23.06.2021 10:52 schrieb JDFiX ***@***.***>:
If there is a way to make the night brighter?
