### ISSUE TITLE
Improve GMP detection

### ISSUE THREAD

**Issue by Reveares** [Kirides/GD3D11#57]
The current implementation simply checks if the gmp.dll is in `{Gothic Path}/system/gmp.dll` or `{Gothic Path}/gmp/gmp.dll`.
https://github.com/Kirides/GD3D11/blob/master/D3D11Engine/DLLMain.cpp#L201

The Problem is that these paths are only valid if spine or a really old GMP version is used. Otherwise, the gmp.dll could be anywhere as it is in the GMP launcher which could be installed anywhere.

Better would be to check with the win32 api if the `gmp.dll` is currently loaded by the Gothic process. I think `GetModuleHandle` can do this, but I'm not an expert on the win32 api.

**Comment by Reveares** [comment]
I will look into implementing this issue and provide a PR when done if you are fine with my suggestion.

**Comment by Kirides** [comment]
Feel free :)Am 06.07.2021 20:10 schrieb Reveares ***@***.***>:
I will look into implementing this issue and provide a PR when done if you are fine with my suggestion.
