### ISSUE TITLE
Dev 19 problems

### ISSUE THREAD

**Issue by postm1** [Kirides/GD3D11#59]
Hi, I checked the dev 19, it is nice, but there is a problem
In some locations, there are some Visual effects on the screen space.
![1](https://user-images.githubusercontent.com/2078377/124344625-10701100-dbdc-11eb-8363-93b853395c32.jpg)
![23](https://user-images.githubusercontent.com/2078377/124344696-7eb4d380-dbdc-11eb-963c-1c9328e75196.jpg)

You can see some fire in the screen. It renders on the screen space, e.g. when I move camera, it moves with the camera, and renders again. When this bug occured no any visual effect works in the location. Magic visual effects dont work either (only when the bug occurs)
In some location all work fine. No idea why it is happening.

There is **no bug in dev 18**. Checked.

**Comment by postm1** [comment]
![1123](https://user-images.githubusercontent.com/2078377/124344979-88d7d180-dbde-11eb-9553-6014d4a956ce.jpg)
Also I guess you meant another variable ;)

**Comment by Kirides** [comment]
Yea, that new option is currently useless, as dev19 sadly reversed a bunch of changes, including the fps lock.I'll have to reintroduce it later, when I get some time again.Also, do the graphical glitches only appear as of dev19? I know that some graphical effects are just 2d sprites that move with the player (some fires, like candles)

**Comment by postm1** [comment]
Bug with visual effect is only in dev 19 (no in dev 18, I checked it).
In some locations **all the effects** (including hero's magic, usual fire) don't work + some effect on the screen space occur.

**Comment by Kirides** [comment]
Jup, just reproduced the issue. Will have to look at the changed code. Thanks for raising this issue!

**Comment by postm1** [comment]
So, you have the bug too? If you have it is ok ;) I thought it was something in AB mode ;)

**Comment by Kirides** [comment]
Jup also found the introducing commit. There will be an update shortly, that reverses the commit for now.
