### ISSUE TITLE
Dev 19 Texture issue

### ISSUE THREAD

**Issue by postm1** [Kirides/GD3D11#60]
![162531023018_kiss](https://user-images.githubusercontent.com/2078377/124347643-60f06a00-dbee-11eb-9330-8f43086685f8.jpg)
When changing the chapter or location, texture is bugged. 
Works since **Dev 19**
No bug in Dev 18
;)

**Comment by Kirides** [comment]
Wait for fix1 release in a few minutes and try again please :)

**Comment by Kirides** [comment]
Update is out now.

**Comment by postm1** [comment]
Textures and PFX are ok now ;) Thanks.

**Comment by Kirides** [comment]
Just saw that @SaiyansKing pushed two new commits 8 hours ago. Will check if these fix the issue on their own.

**Comment by Kirides** [comment]
@postm1 would you mind, testing the https://github.com/Kirides/GD3D11/releases/tag/v17.7-dev19-fix2 in Returning for me?

It seemed to work fine in G2 NotR, PFX and chapter screen worked there.

**Comment by postm1** [comment]
It works fine ;)
