### ISSUE TITLE
Ghost npc

### ISSUE THREAD

**Issue by postm1** [Kirides/GD3D11#65]
Hi, I've seen "properly render "ghosts" with transparency" in the changelog.
But there is no effect in the game (AB mod).
Or it works only in usual G2?
How to check ghost npc?

Btw, it is me, Liker_Gothic

**Comment by Kirides** [comment]
Check orc ghosts in VoM or Quarhodron.Streamer Plasquar showed that orc ghosts in old orc village are transparent

**Comment by postm1** [comment]
![123](https://user-images.githubusercontent.com/2078377/125489981-c2f4b3f3-eb34-44fa-8973-34d417a10dd6.jpg)
That is orc ghost and Quarhodron in New Balance. Not transparent ;(

**Comment by postm1** [comment]
Can you show the stream with transparent orcs? I can't find it (exactly stream)

**Comment by Kirides** [comment]
sadly i couldn't find it anymore.
Though here is a image from G2A. Do you have `NPC_FLAG_GHOST` on the ghost NPC set?
![grafik](https://user-images.githubusercontent.com/13602143/125511152-9c61dc3c-1c08-4617-93af-34afc882dbc3.png)

**Comment by postm1** [comment]
All npcs have that flag... Strange.

**Comment by postm1** [comment]
What mod is it? on the screen

**Comment by Kirides** [comment]
It's regular Gothic 2 NotR (but with texture patches)

**Comment by postm1** [comment]
So, somehow it does not work in New Balance.
I will try to find the problem.

**Comment by Kirides** [comment]
The renderer looks for transparency at Address 0xAB26A4

**Comment by Kirides** [comment]
`oCNpc::InitByScript` should initialize this variable. it's read from here, and defaults to `0.3f`

```ini
[INTERNAL]
GhostAlpha
```

**Comment by postm1** [comment]
yeah, on usual G2NR with union it works fine. 
Wtf ;(

**Comment by Kirides** [comment]
i've built a version with static 0.3f transparency, can you check if it helps?
[ddraw.zip](https://github.com/Kirides/GD3D11/files/6814766/ddraw.zip)

**Comment by postm1** [comment]
Does not work on a new build ;( 
GhostAlpha is ok in gothic.ini
Strange ;(

**Comment by postm1** [comment]
Could it be due to new armors and models in Returing 2.0?

**Comment by Kirides** [comment]
can you show marvin `edit focus`, `flags` value of the NPCs ?

Idk if the new models cause the renderer to not recognize them as "skeletal meshes" but ... as Vobs/Mobs.
Can you test in CTRL+F11 to disable rendering of all _but_ skeletal mesh vobs?

**Comment by postm1** [comment]
![image](https://user-images.githubusercontent.com/2078377/125594348-a7fdf46f-e911-4f8c-afbe-e306ca3abdb2.png)

All npc has that flag.
No marvin, but our panel info ;)

**Comment by postm1** [comment]
![image](https://user-images.githubusercontent.com/2078377/125594507-41fdf74d-c396-4d1d-8873-d74e0d3aca66.png)

All of them are skeleal meshes ;)

**Comment by Kirides** [comment]
Can you test this ddraw.dll? It skips the flag check and just assumes all flags are set.
[ddraw.zip](https://github.com/Kirides/GD3D11/files/6814844/ddraw.zip)

**Comment by postm1** [comment]
![image](https://user-images.githubusercontent.com/2078377/125595056-94981307-6a07-4459-86e2-452f0f5c6345.png)
nope, not transparent ;( all npcs on the scene are ghosts

**Comment by postm1** [comment]
So, flags are ok. May be some setting which turn off the rendering?

**Comment by Kirides** [comment]
There is no special handling for ghosts, other than the flag check :/ (well, and the queuing of the npcs to be drawn at ghost stage)

Can you check this dll. It should spam your Log.txt with mentions of the rendered Ghost NPC
[ddraw.zip](https://github.com/Kirides/GD3D11/files/6814887/ddraw.zip)

**Comment by Kirides** [comment]
You did mention you overrode a bunch of stuff in returning.
Did you perhaps also subclassed oCNpc?

The renderers NPC check might not work for returning then.
It checks that V-Table of Vob points to `0x83D724`.

Hmm. is there a better way to check for an Vob to be an npc?

**Comment by postm1** [comment]
Yes, oCNpc is extended, I will try to turn it off.
[Log.txt](https://github.com/Kirides/GD3D11/files/6814941/Log.txt)

**Comment by postm1** [comment]
vob->vobtype == zVOB_TYPE_NSC (130) try this

**Comment by postm1** [comment]
"type" has 0x00B0 offset ;)

**Comment by Kirides** [comment]
i might've found a "better" solution. i will come back in a few minutes with a new test build for you.

**Comment by Kirides** [comment]
Can you check this? This now walks the inheritance graph in G2A and checks for OCNPC inheritance
[ddraw.zip](https://github.com/Kirides/GD3D11/files/6815110/ddraw.zip)

**Comment by postm1** [comment]
![image](https://user-images.githubusercontent.com/2078377/125600765-33a896f2-9a32-47bd-b2eb-a03897c9c178.png)
Nice ;)

**Comment by Kirides** [comment]
FPS will be a bit lower with that version, as the npc check is currently string-based. i will optimize that check to a simple pointer check later

**Comment by postm1** [comment]
If you can, do it before 17 of July, there will be a new update for New Balance ;)

**Comment by Kirides** [comment]
fixed with latest release dev19-fix4
