### ISSUE TITLE
No barrier in G2NOTR 

### ISSUE THREAD

**Issue by Fabiosek** [Kirides/GD3D11#71]
Hi. The Magic Barrier is not visible in G2NOTR. Since I am making a modification that MUST support DX11, it would be very useful for me to have the magic barrier visible.

Screenshot:
https://cdn.discordapp.com/attachments/590443253292335114/867068224846823444/skrin1.jpg

PS. I use Union (1.0k), the barrier plugin is from Gratt. 
PS2. I tested on the latest version of "release".

**Comment by Kirides** [comment]
Did you try disabling "Atmospheric Scattering" in the advanced options?

**Comment by Fabiosek** [comment]
Advanced options from original game or "DX11"?

I started the window with "dx11 settings" with the Printscreen key, but you can't click anything there - there is no cursor. 

PS. It is not possible to switch the resolution in the main menu (although this is a different problem)

**Comment by Kirides** [comment]
Atmospheric Scattering is found in the CTRL+F11 menu of the dx11 renderer. It's somewhere at the end of the seconds tab/column.

Yes. You can not change the resolution from inside the game, you have to set resolution via F11 menu, click apply(*) and restart the game for it to properly work
