### ISSUE TITLE
G2 videos arent stretched 

### ISSUE THREAD

**Issue by PijanyStary** [Kirides/GD3D11#75]
Playing with the AVX2 version and also Union, 1920x1080 resolution. It happens regardless of video scaling being set to 0 or 1, fullscreen or windowed.
![Screenshot_6](https://user-images.githubusercontent.com/72890545/127550201-22078c5b-4fe8-48b1-95c9-f7607eba2506.png)
If I deactive D3D11 the videos are fullscreen again provided I set scaleVideo=0

**Comment by Kirides** [comment]
Disable "FixBink" in SystemPack.ini and set scaleVideos=0 in Gothic.ini

**Comment by PijanyStary** [comment]
Unfortunately it didnt work for me

**Comment by Kirides** [comment]
I need a lot more information about your environment.What mods are installed, what plugins, patches etc.I know for sure that current union works fine with renderer and stretched videos with the aforementioned settings. This is what I run in all my streams and playthroughs

**Comment by PijanyStary** [comment]
I have the gold edition of the game on steam which already includes the 2.6 patch. I installed the System Pack 1.9 and 4GB patch along with Union 1.0k, through the Resource Manager. I use the v17.7-dev20_avx2 version of the renderer. 

That's all I use. I can attach the various .ini files if that's any help

**Comment by Kirides** [comment]
Yes please, you can attach the files themselves in here (do not just copy the contents of them)

**Comment by PijanyStary** [comment]
[gothic.txt](https://github.com/Kirides/GD3D11/files/6913324/gothic.txt)
[SystemPack.txt](https://github.com/Kirides/GD3D11/files/6913325/SystemPack.txt)
[UserSettings.txt](https://github.com/Kirides/GD3D11/files/6913326/UserSettings.txt)

**Comment by Kirides** [comment]
Until I get back to a PC with Gothic: can you try to set FixBink=0 (also no spaces) instead of `FixBink = False`Iirc..there was once an issue where union/Systempack interpreted everything that was not exactly =0 as "enabled"I will check this tomorrow/in ~12-20 hrs depending on if I can get onto my PC. :)

**Comment by PijanyStary** [comment]
Thank you, setting FixBink=0 worked so it seems the issue you mentioned is still around
