### ISSUE TITLE
Exception on khorinis world

### ISSUE THREAD

**Issue by LDS1** [Kirides/GD3D11#78]
dev 20 version, on dev 17 it was ok. Proton 6.3, steamfix

![image](https://user-images.githubusercontent.com/8604295/130377557-fc85f245-1af9-41e8-862a-e773b7d314c0.png)

======================================= UNHANDLED EXCEPTION OCCURED ======================================================
======================================= CRASH INFOS: =====================================================================
Gothic II - 2.6 (fix), Parser Version: 50
User:  steamuser,  CPUType: 586,  Mem: 0 MB total, 0 MB free
Startup Options:-game:g2a_nr_scriptpatch_v26.ini
=============================================== CALLSTACK : ==============================================================
0023:015B03A6 (0x02549510 0x00000000 0x00000000 0x025369D8) DDRAW.dll
0023:016066D8 (0x0082E6F0 0x30B672E8 0x309E4AC8 0x0065783F) DDRAW.dll, RegisterSpecialCase()+74536 byte(s)
0023:015FC5F2 (0x0554ECC8 0x006C6CF4 0x3262DCA8 0x00000000) DDRAW.dll, RegisterSpecialCase()+33346 byte(s)
0023:016147D7 (0x3262DCA8 0x00000000 0x008CDC70 0x00000000) DDRAW.dll, RegisterSpecialCase()+132135 byte(s)
0023:006C6CF4 (0x00000002 0x1004FA1D 0xFFFFFFFF 0x00000001) GothicMod.exe, oCGame::LoadSavegame()+1316 byte(s), P:\dev\g2addon\release\Gothic\_ulf\oGame.cpp, line 2249
0023:0081A1DC (0x00000000 0x006C1C5E 0x0554CA08 0x0042A282) GothicMod.exe, SetFileAttributesA()+222744 byte(s)
0023:007E8E48 (0x0044FFF0 0x00423E50 0x00423F90 0x00450000) GothicMod.exe, SetFileAttributesA()+21124 byte(s)
0023:00424010 (0x005ABDD0 0x0076FB80 0x005ABB30 0x0076FBE0) GothicMod.exe, oCGameInfo::Init, P:\dev\g2addon\release\Gothic\_bert\oGameInfo.cpp, line 67
0023:005AB940 (0x005ABDD0 0x005ABE30 0x005ABB30 0x00426C90) GothicMod.exe, zCObjectFactory::CreateZFile, P:\dev\g2addon\release\ZenGin\_dieter\zObject.cpp, line 784
0023:005AB940 (0x004DB910 0x10050530 0x004DCCD0 0x004DC1C0) GothicMod.exe, zCObjectFactory::CreateZFile, P:\dev\g2addon\release\ZenGin\_dieter\zObject.cpp, line 784

**Comment by Kirides** [comment]
Could you provide a bit more infor about your environment, aswell as the failing (zipped) savegame for debugging purposes?

**Comment by LDS1** [comment]
Closing the issue because switching from proton 6.3 to experimental fixes it.
