### ISSUE TITLE
Huge FPS drop near light sources

### ISSUE THREAD

**Issue by LDS1** [kirides/GD3D11#80]
I experience big fps drop near fireplaces, torches, candles, etc. Even one torch has impact, if there are few of them in sight everything goes much worse.

Intel HD 630. It shows about 20 fps with FX off. Near old Xardas tower in the valley 25 fps goes to 10 inside the tower. 
 
![image](https://user-images.githubusercontent.com/8604295/131176103-9f9f676f-5344-4aa5-b6f6-e9e85ef84371.png)

**Comment by LDS1** [comment]
@Kirides Seems like it's duplicate of https://github.com/Kirides/GD3D11/issues/2 and not intel related

**Comment by Kirides** [comment]
The issue seems to be in GPU bound scenarios

Works fine on a lot of devices (amd rx 460 easily does 60-100 fps, my rtx 2080 doesn't mind if i look at a torch or not -> CPU bound)
don't have a card that is weak enough to pin-point the exact place that produces the "lag"

**Comment by LDS1** [comment]
Performance drop was caused by dynamic shadows on low end gpu. It's normal behavior
