### ISSUE TITLE
Freeze on tessellation on  

### ISSUE THREAD

**Issue by LDS1** [kirides/GD3D11#82]
Game freezes when I turn on tessellation in F11 menu. 

Intel HD 630, Proton experimental and 6.3.

**Comment by Kirides** [comment]
Can you post the log.txt of the game session that freezes?I guess it has something to do with Intel and general shader support. As Intel GPUs not even work on windows Machines.( And are unsupported by me, as I don't own an Intel device)

**Comment by LDS1** [comment]
[Log1.txt](https://github.com/Kirides/GD3D11/files/7071511/Log1.txt)
[Log.txt](https://github.com/Kirides/GD3D11/files/7071516/Log.txt)

`Log` is for game started with tesselation on, `Log2` is when I tried to turn it on inside the game session.

**Comment by LDS1** [comment]
[Log.txt](https://github.com/Kirides/GD3D11/files/7072801/Log.txt)
With debug on

**Comment by LDS1** [comment]
fixed in this fork https://github.com/SaiyansKing/GD3D11
