### ISSUE TITLE
EnableOcclusionCulling=1 makes screen black

### ISSUE THREAD

**Issue by LDS1** [kirides/GD3D11#84]
But it actually doesn't break the game, another click while screen is black turns culling off and everything is fine again.

**Comment by Kirides** [comment]
Log?

**Comment by LDS1** [comment]
[Log.txt](https://github.com/Kirides/GD3D11/files/7073055/Log.txt)

**Comment by kirides** [comment]
Does it still happen in the newly released v17.8-dev1?

**Comment by LDS1** [comment]
It still breaks the game.

Note:
Initially I've tested on linux proton.
Currently testing on macbook with m1pro running parallels on win11 on arm.

**Comment by LDS1** [comment]
Not crashing on 17.8 dev2, but vobs are not displaying

**Comment by LDS1** [comment]
Closed in favor of https://github.com/SaiyansKing/GD3D11/issues/23
