### ISSUE TITLE
please update targets in readme.md 

### ISSUE THREAD

**Issue by stefson** [kirides/GD3D11#89]
I browsed through the project file with msvc community 2019, and noticed there are new targets available. 

Launcher: unknown
Release: Gothic2 release? 
Release_AVX: Gothic2 with AVX?
Release_G1: Gothic1
Release_G1_12f: unknown
Release_G1_AVX: Gothic1 with AVX?
Release_NoOpt: Gothic2 debug release?
Release_NoOpt_G1: Gothic1 debug release?
Release_NoOpt_Spacer: unknown
Space_Net: unknown

can you please be so kind to update these descriptions, to reduce confusion?

**Comment by kirides** [comment]
Spacer_NET is obviously a target for... Spacer_NET

G1_12f is gothic sequel.

Everything else is correct.

**Comment by Kor-Angar** [comment]
render for G1_12f is gothic sequel ?
