### ISSUE TITLE
Changes to advanced settings do not get saved

### ISSUE THREAD

**Issue by qwelias** [Kirides/GD3D11#9]
1. Press Ctrl+F11
2. Uncheck DynamicLighting
3. Click Apply
4. Restart the game
5. Alas, DynamicLighting is enabled

**Comment by Kirides** [comment]
This is the only relevant lightning setting that was not saved yet.

fixed in [87b5166](https://github.com/Kirides/GD3D11/commit/87b516669106a597e717f08c203a232642324efa)

**Comment by pokorm** [comment]
What about `ReplaceSunDirection` mentioned [here](https://www.reddit.com/r/worldofgothic/comments/em8heq/gothic_2_d3d11_clockwork_edition_why_cant_i_save/)?

**Comment by Kirides** [comment]
Added that (and the direction vector) in fc168b0

**Comment by diolator** [comment]
I also tried to save SMAA - Sharpen and Sun light brightness but it didnt save. Every time i launch the game i need to set setting again.

**Comment by Kirides** [comment]
@diolator what version of the Renderer so you use?

SMAA is saved since dev1.
The changes of this commit are not available as a release, I haven't had for that yet

**Comment by diolator** [comment]
@Kirides the last version which is 17.7 dev8

You were right, SMAA can be saved, but what about other settings? I wish i could save SunLightStrenght, ShadowAOStrenght, ShadowStrenght and Atmospheric Scattering

Besides that, what are plans for future shaders? Subsurface Scattering? Parallax Mapping?
But the most needed thing atm is Moon light source i think.

**Comment by diolator** [comment]
@Kirides Also, is there any solution for shimmering self shadows on meshes?
