### ISSUE TITLE
unable to copy shaders when building with mscv2019 community edition

### ISSUE THREAD

**Issue by stefson** [kirides/GD3D11#90]
```
in Projekt D3D11Engine
in Datei Microsoft.CppCommon.targets, Zeile 286

Der Befehl "copy "shaders\*.*" "\GD3D11\shaders\"
copy "C:\Users\name\Downloads\GD3D11-17.8-dev1_rl\GD3D11-17.8-dev1_rl\Release\ddraw.dll" "\ddraw.dll"
copy "C:\Users\name\Downloads\GD3D11-17.8-dev1_rl\GD3D11-17.8-dev1_rl\Release\ddraw.pdb" "\ddraw.pdb"
:VCEnd" wurde mit dem Code1 beendet.
```
I was unable to find that targets file in the src dir, only that it is referenced in `D3D11Engine/D3D11Engine.vcxproj`

**Comment by kirides** [comment]
it tries to copy dll & shaders into the games directory.
Depending on the game, you have to set `G2_SYSTEM_PATH` to e.g. `C:\games\Gothic2\system`

All that is optional though and can be done manually.
