### ISSUE TITLE
UI scale is not working with 4K resolution

### ISSUE THREAD

**Issue by heroutm** [kirides/GD3D11#94]
Hello,

UI scale option is not working with 2160p.
UI in conversation disappers completly. 

![image](https://user-images.githubusercontent.com/38924821/147714324-9f7fb614-376a-4a3d-9a6c-b492082d3781.png)

**Comment by kirides** [comment]
UIScale doesn't exist anymore.Use Systempack/Union scaling Am 30.12.2021 02:21 schrieb heroutm ***@***.***>:
Hello,
UI scale option is not working with 2160p.
UI in conversation disappers completly.
